#ifndef GALAXY_INVADERS_DOMAIN_CONSTANTS_H
#define GALAXY_INVADERS_DOMAIN_CONSTANTS_H

/* Pure domain constants. No dependency on any rendering or platform library. */

#define SCREEN_W 480
#define SCREEN_H 640

#define TARGET_FPS 60

#define MAX_PLAYER_PROJECTILES 32
#define MAX_ENEMY_PROJECTILES 64
#define MAX_ENEMIES 48
#define MAX_EXPLOSIONS 32
#define MAX_STARS 80
#define MAX_EVENTS 16

#define PLAYER_WIDTH 32.0f
#define PLAYER_HEIGHT 22.0f
#define PLAYER_SPEED 240.0f
#define PLAYER_FIRE_COOLDOWN 0.18f
#define PLAYER_MIN_Y (SCREEN_H * 0.45f)
#define PLAYER_MAX_Y (SCREEN_H - 40.0f)

#define PLAYER_PROJECTILE_W 3.0f
#define PLAYER_PROJECTILE_H 14.0f
#define PLAYER_PROJECTILE_SPEED 520.0f

#define ENEMY_PROJECTILE_W 6.0f
#define ENEMY_PROJECTILE_H 8.0f
#define ENEMY_PROJECTILE_SPEED 260.0f
#define ENEMY_FIRE_CHANCE_PER_SEC 0.35f

#define ENEMY_MIN_SIZE 15.0f
#define ENEMY_MAX_SIZE 25.0f
#define ENEMY_BASE_SPEED 55.0f
#define ENEMY_SPEED_PER_1000_SCORE 15.0f
#define ENEMY_MAX_SPEED 220.0f

#define BASE_SPAWN_INTERVAL 1.10f
#define MIN_SPAWN_INTERVAL 0.22f
#define SPAWN_INTERVAL_STEP_SCORE 500.0f
#define SPAWN_INTERVAL_STEP_FACTOR 0.92f

#define SCORE_PER_KILL 10
#define SCORE_MULTIPLIER_STEP 500.0f
#define SCORE_MULTIPLIER_INCREMENT 0.1f

#define EXPLOSION_DURATION 0.28f

#endif
